/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-05-31 14:03:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import java.io.*;

public final class download_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"backgrounds.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#Layer1 {\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\twidth:1096px;\r\n");
      out.write("\theight:115px;\r\n");
      out.write("\tz-index:1;\r\n");
      out.write("\ttop: 14px;\r\n");
      out.write("}\r\n");
      out.write("#Layer2 {\r\n");
      out.write("\tposition:absolute;\r\n");
      out.write("\twidth:1097px;\r\n");
      out.write("\theight:1075px;\r\n");
      out.write("\tz-index:2;\r\n");
      out.write("\tleft: 12px;\r\n");
      out.write("\ttop: 133px;\r\n");
      out.write("}\r\n");
      out.write(".submit\r\n");
      out.write("{\r\n");
      out.write("background-image:url(Images/Download.png);\r\n");
      out.write("width:95px;\r\n");
      out.write("hieght:300px;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-image:url(Images/finalb.jpg); background-repeat:no-repeat; \">\r\n");
      out.write("\r\n");
      out.write(" <img src=\"Images/head1.jpg\"  width=\"100%\" height=\"124\" align=\"center\"/>  \r\n");
      out.write(" ");
 
//HttpSession sess=request.getSession(false);
String usern=session.getAttribute("name").toString();

if(usern!=null)
{
 out.println("<p style='float:right; margin:0; font-weight:bold; color:brown;font-size:20px;background-color:#33CCCC ;border: 2px solid black; opacity: 0.9;'> Welcome: "+usern+" ");	
 out.println("<ul><li><a href='SearchAfterLogin.jsp'>Home</a></li>");
}
else
	out.println("<ul><li><a href='Search.jsp'>Home</a></li>");
	

      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <li><a href=\"#news\">User</a></li>\r\n");
      out.write("  <li><a href=\"#about\">About</a></li>\r\n");
      out.write("<li><a href=\"login.html\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"Layer1\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");



try{
Database db=new Database();
Connection con=db.dataConnection();
Byte song;
String id = request.getQueryString();
out.println(id);

Statement stmt=con.createStatement();

String str="Select * from song where songid='"+id+"' ";
String[] d= new String[10];
int i=0;
ResultSet rs=stmt.executeQuery(str);
System.out.println(rs.getRow());
out.println("<html>");

out.println("<body>");

out.println("<form method='post' action='Save.jsp'><p>&nbsp;</p> ");
out.println("<div class='background' height='332px' width='603'>");
out.println("<font color='red' size='6px'>Search Results:</font>");
out.println("<table  width='603' height='332' border='10' align='center' bordercolor='#FFFF00' >");

while(rs.next())
{
 out.println("<tr><td width='207' align='center' class='style1 subtitle'><span class='style2'>"+rs.getString(1)+"</td><td width='207' class='style1 subtitle'><span class='style2'>"+rs.getString(2)+"</td><td><input type='submit' name='download' class='submit'   value="+rs.getString(2)+"></td></tr>");	
  //rs.getString(2).toCharArray(); 
 System.out.println("Down"+rs.getString(2));
 d[i]=rs.getString(1);
  
}


//response.setContentType("audio/mp3");

//String path=request.getParameter("download");
//application.setAttribute("abc",path);
//System.out.println(path);

out.println("</table>");
}catch(Exception e)
{
out.println();
	}
out.println("</div>");
out.println("</form>");
out.println("</body>");
out.println("</html>");


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
