/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2015-05-31 13:53:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import process.matchingcode;
import matching.editdistance;
import java.io.*;

public final class maintain_005fhist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


        int sid = 0;
         Database db=new Database();
          Connection con=db.dataConnection();
        

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"backgrounds.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url(\"table\");\r\n");
      out.write(".style1 {font-size: 24px}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".style2 {\r\n");
      out.write("\tfont-family: \"Comic Sans MS\";\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-image:url(Images/finalb.jpg); background-repeat:no-repeat; \">\r\n");
      out.write(" <img src=\"Images/head1.jpg\"  width=\"100%\" height=\"124\">\r\n");
      out.write(" ");
 
//HttpSession sess=request.getSession(false);
String usern=session.getAttribute("name").toString();

if(usern!=null)
{
 out.println("<p style='float:right; margin:0; font-weight:bold; color:brown;font-size:20px;background-color:#33CCCC ;border: 2px solid black; opacity: 0.9;'> Welcome: "+usern+" ");	
 out.println("<ul><li><a href='SearchAfterLogin.jsp'>Home</a></li>");
}
else
	out.println("<ul><li><a href='Search.jsp'>Home</a></li>");
	

      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <li><a href=\"#news\">User</a></li>\r\n");
      out.write("  <li><a href=\"#about\">About</a></li>\r\n");
      out.write("<li><a href=\"login.html\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");

            try
            {
                int hid=0,flag=0;
                String sname=null;
                String name=null;
                    String song = request.getParameter("song");
                    System.out.println("song"+song);
                    Integer id = (Integer)session.getAttribute("songid");
                 out.println(id);
                 String uname = (String)session.getAttribute("name");//get userid from session
                String query = (String)session.getAttribute("query");
                out.println(uname);
                out.println(query);
               
            Statement stmt=con.createStatement();
              
             String str1="select hid from qbsh_searchhistory";
             ResultSet rs=stmt.executeQuery(str1);
              while(rs.next())
              {
                  hid=rs.getInt(1);
              }
              hid++;
              
              Statement stt = con.createStatement();
              String ss = "Select songid from song where songtitle like '%"+song+"%'";
              ResultSet rr = stt.executeQuery(ss);
              while(rr.next())
              {
                  sid = rr.getInt(1);
                  System.out.println("Song id " +sid);
              }
              
              String str2="select user_id,songname from qbsh_searchhistory where songid='"+sid+"'";
               ResultSet r1 = stt.executeQuery(str2);
               while(r1.next())
               {
                   name=r1.getString(1);
                   sname=r1.getString(2);
               }
               if(song.equals(sname) && uname.equals(name)) //to avoid duplicate query      
                   {
                      flag=0; 
                   }
                   else
                   {
                      flag=1; 
                   }
               System.out.println("flag="+flag+"\t"+name);
               if(flag==1)
               {
                   String str="insert into qbsh_searchhistory values(?,?,?,?,?)";
                   PreparedStatement ps=con.prepareStatement(str);
                   ps.setInt(1,hid);
                   ps.setString(2,uname);
                   ps.setString(3,query);
                   
                   ps.setString(5,song);
                   if(sid==0)
                	   sid=1;
                   
                   ps.setInt(4,sid);
                   boolean i=ps.execute();
              
                   if(i=true)
                   {
                     response.sendRedirect("feedback.jsp?sucess");
                   }
                   ps.close();
                 }
                 if(flag==0)
                 {
                     response.sendRedirect("feedback.jsp?sucess");
                 }
              
              
       } 
             
            catch(Exception e)
            {
                out.println(""+e);
            }
        
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
