/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-04-11 09:46:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AudioFileUpload_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"backgrounds.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url(\"table\");\r\n");
      out.write(".style1 {font-size: 24px}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".style2 {\r\n");
      out.write("\tfont-family: \"Comic Sans MS\";\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-image:url(Images/finalb.jpg); background-repeat:no-repeat; \">\r\n");
      out.write("<form method=\"post\" action=\"AudioFileUpload\" >\r\n");
      out.write(" <img src=\"Images/head1.jpg\"  width=\"100%\" height=\"124\">\r\n");
 
String usern=session.getAttribute("name").toString();
if(usern!=null)
{
 out.println("<p style='float:right; margin:0; font-weight:bold; color:brown;font-size:20px;background-color:#33CCCC ;border: 2px solid black; opacity: 0.9;'> Welcome: "+usern+"</p>");	
 
}

      out.write("\r\n");
      out.write("   \r\n");
      out.write(" <ul>\r\n");
      out.write("  <li><a href=\"Admin.jsp\">Home</a></li>\r\n");
      out.write(" <li><a href=\"AudioFileUpload.jsp\">Upload Song</a></li>\r\n");
      out.write(" \r\n");
      out.write("  <li><a href=\"#about\">About</a></li>\r\n");
      out.write("<li><a href=\"AdminLogin.html\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("  \r\n");
      out.write("   <div class=\"background1\" height=\"332px\" width=\"603\" >\r\n");
      out.write("   <table width=\"603\" height=\"332\" border=\"10\" align=\"center\" bordercolor=\"#FFFF00\" class=\"table\">\r\n");
      out.write("   \r\n");
      out.write("     <tr>\r\n");
      out.write("       <td width=\"207\" class=\"style1 subtitle\"><span class=\"style2\"> Song ID </span></td>\r\n");
      out.write("       <td width=\"384\"><input name=\"id\" type=\"text\" class=\"style1\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td class=\"style1 subtitle\"><span class=\"style2\">Song Title </span></td>\r\n");
      out.write("       <td><input name=\"stitle\" type=\"text\" class=\"style1\">\r\n");
      out.write("       </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td class=\"style1 subtitle\"><span class=\"style2\"> Genre </span></td>\r\n");
      out.write("       <td><input name=\"genre\" type=\"text\" class=\"style1\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td class=\"style1 subtitle\"><span class=\"style2\"> Year </span></td>\r\n");
      out.write("       <td><input name=\"year\" type=\"text\" class=\"style1\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("       <td class=\"style1 subtitle\"><span class=\"style2\"> Tempo </span></td>\r\n");
      out.write("       <td>\r\n");
      out.write("                       <select class=\"field small-field\" name=\"tempo\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Slow\">slow</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Fast\">Fast</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Very Fast\">Very Fast</option></select>\r\n");
      out.write("\t   </td>                                                   \r\n");
      out.write("       \r\n");
      out.write("     </tr>\r\n");
      out.write("      <tr>\r\n");
      out.write("       <td class=\"style1 subtitle\"><span class=\"style2\"> Singer Gender </span></td><td>\r\n");
      out.write("        <select class=\"field small-field\" name=\"s_gender\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Female\">Female</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"Male\">Male</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td class=\"style1 subtitle\"><span class=\"style2\"> Song </span></td>\r\n");
      out.write("       <td><input name=\"song\" type=\"file\" class=\"style2\" value=\"\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("       <td><input name=\"button\" type=\"file\" class=\"style2\"  value=\"Click Here to upload MIDI file \">Click Here to upload MIDI file </td>\r\n");
      out.write("     </tr>\r\n");
      out.write("     \r\n");
      out.write("     <tr>\r\n");
      out.write("       <td><input name=\"submit\" type=\"submit\" class=\"style2\" style=\"width:100px; Height:24px;\" value=\"Save\"></td>\r\n");
      out.write("     </tr>\r\n");
      out.write("   </table>\r\n");
      out.write("   </div>\r\n");
      out.write("   <p><br>\r\n");
      out.write("  </p>\r\n");
      out.write("   <p><br>\r\n");
      out.write("     <br>\r\n");
      out.write("    </p> \r\n");
      out.write("  <p>&nbsp;</p>\r\n");
      out.write("</form>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
