/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-04-11 09:49:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import java.io.*;

public final class Save_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");

try{
	/*String s=(String)application.getAttribute("abc");*/
	String path=request.getParameter("download");
	System.out.println("Save"+path);
	InputStream is=null;
	byte[] vi=new byte [1024*1024*2];
	int size=0;
	Database db=new Database();
	Connection con=db.dataConnection();
	Statement stmt=con.createStatement();
	Blob file1= null;

	String str="Select * from song where songtitle like '%"+path+"%' ";
	ResultSet rs=stmt.executeQuery(str);
	response.reset();
	String s=null;
	while(rs.next())
	{
	s= rs.getString(2); 
	
	file1=rs.getBlob(3);
	response.reset();
	 is=(rs.getBinaryStream(3));
	//int filelength=inputstream.available();
	//	out.println(s);

	
	//response.reset();
	/*	while((size=is.read(vi))!=-1)
		{
			System.out.println("Read");
			String name=path;
			response.setHeader("Content-Type", "audio/mp3");	
			response.setContentType("audio/mp3");
			response.addHeader("Content-Disposition", "attachment;filename='"+name+"'");
			response.getOutputStream().write(vi,0,size);
	 		
			out.println("</audio>");
		}*/
		
	 byte[] ba = file1.getBytes(1, (int)file1.length());
		String filename=path;
		
			response.setContentType("application/mp3");
			response.setHeader("Content-Disposition","attachment; filename=\""+path+".mp3"+"\"");
			OutputStream os = response.getOutputStream();
			
			
			os.write(ba);
			

			os.close();
			
			
	}
	/*	*/
	
}catch(Exception e)
{
	//out.println("<script type='text/javascript'>function myFunction() {alert('Dear user, your Query has been loaded.');}" +	"window.onload=myFunction();</script>");
out.println("msg"+e.getMessage());
}


      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
