/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-04-11 09:39:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SearchAfterLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"SearchBar.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var c = 0;\r\n");
      out.write("var t;\r\n");
      out.write("var timer_is_on = 0;\r\n");
      out.write("\r\n");
      out.write("function timedCount() {\r\n");
      out.write("    document.getElementById(\"txt\").value = c;\r\n");
      out.write("    if(c<30)\r\n");
      out.write("    c = c + 1;\r\n");
      out.write("    else\r\n");
      out.write("    \tclearTimeout(t);\r\n");
      out.write("    timer_is_on = 0;\r\n");
      out.write("    t = setTimeout(function(){timedCount()}, 1000);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function startCount() {\r\n");
      out.write("    if (!timer_is_on) {\r\n");
      out.write("        timer_is_on = 1;\r\n");
      out.write("        timedCount();\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("ul {\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    width:800px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("    float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:link, a:visited {\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 120px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #FFFFFF;\r\n");
      out.write("    background-color: #98bf21;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    padding: 4px;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a:hover, a:active {\r\n");
      out.write("    background-color: #7A991A;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div.background {\r\n");
      out.write("    background-color:#33CCCC ;\r\n");
      out.write("    border: 2px solid black;\r\n");
      out.write("    opacity: 0.9;\r\n");
      out.write("    filter: alpha(opacity=60); /* For IE8 and earlier */\r\n");
      out.write("    width:700px;\r\n");
      out.write("    height:250px;\r\n");
      out.write("   margin-left:320px;\r\n");
      out.write("   \r\n");
      out.write("     padding:0px;\r\n");
      out.write("        \r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-image:url(Images/finalb.jpg); background-repeat:no-repeat;color:white;\">\r\n");
      out.write("\r\n");
      out.write(" <img src=\"Images/head1.jpg\"  width=\"100%\" height=\"124\"/>  \r\n");
      out.write("\r\n");
      out.write(" ");
 
//HttpSession sess=request.getSession(false);
String usern=session.getAttribute("name").toString();

if(usern!=null)
{
 out.println("<p style='float:right; margin:0; font-weight:bold; color:brown;font-size:20px;background-color:#33CCCC ;border: 2px solid black; opacity: 0.9;'> Welcome: "+usern+" ");	
 out.println(" <ul><li><a href='SearchAfterLogin.jsp'>Home</a></li>");
}
else
	out.println("<ul><li><a href='Search.jsp'>Home</a></li>");
	

      out.write("\r\n");
      out.write(" <li><a href=\"Search.jsp\">User</a></li>\r\n");
      out.write("  <li><a href=\"#about\">About</a></li>\r\n");
      out.write("<li><a href=\"login.html\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<form action=\"DownloadSong.jsp\" method=\"post\" > \r\n");
      out.write("<div style=\" margin-left:1000px; align:right;  background-color:#9ACD32;   opacity: 0.9;\r\n");
      out.write("    padding:6px;\">    \r\n");
      out.write("<p>Enter song title to search the song:</p> \r\n");
      out.write("    <input type=\"text\"  name=\"downloads\" size=\"30\" />\r\n");
      out.write("    <input type=\"submit\" name=\"Submit\" value=\"Search\" size=\"20\"/>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("<br />\r\n");
      out.write("  <form action=\"NewServlet\" method=\"post\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"background\"  id=\"timer\">\r\n");
      out.write("  <table style=\"padding:0px;\">\r\n");
      out.write("   <tr><td><input type=\"submit\" name=\"Search\" value=\"Click here to start recording\" onclick=\"startCount()\" style=\"height:150px; width:200px; margin:10px;align:left;\"/></td>\r\n");
      out.write("   <td>Timer:\r\n");
      out.write("   <input type=\"text\" id=\"txt\" size=\"30\"value=\"Sing a song until timer given here is on: \" style=\"font-size:18px;   color:brown; background-color:#33CCCC ;\"/>\r\n");
      out.write("   </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write(" </table>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p align=\"center\">&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("<p>&nbsp;</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
