/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.63
 * Generated at: 2016-04-11 09:42:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import model.Database;
import process.matchingcode;
import java.io.*;

public final class SuccessRecord_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"backgrounds.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("@import url(\"table\");\r\n");
      out.write(".style1 {font-size: 24px}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".style2 {\r\n");
      out.write("\tfont-family: \"Comic Sans MS\";\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-image:url(Images/finalb.jpg); background-repeat:no-repeat; \">\r\n");
      out.write(" <img src=\"Images/head1.jpg\"  width=\"100%\" height=\"124\">\r\n");
      out.write("  ");
 
//HttpSession sess=request.getSession(false);
String usern=session.getAttribute("name").toString();

if(usern!=null)
{
 out.println("<p style='float:right; margin:0; font-weight:bold; color:brown;font-size:20px;background-color:#33CCCC ;border: 2px solid black; opacity: 0.9;'> Welcome: "+usern+" ");	
 out.println("<ul><li><a href='SearchAfterLogin.jsp'>Home</a></li>");
}
else
	out.println("<ul><li><a href='Search.jsp'>Home</a></li>");
	

      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <li><a href=\"#news\">User</a></li>\r\n");
      out.write("  <li><a href=\"#about\">About</a></li>\r\n");
      out.write("<li><a href=\"login.html\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("</ul>\r\n");
      out.write(" \r\n");
      out.write("  <div class=\"background\">\r\n");
      out.write(" <form action=\"processquery\" method=\"post\" id=\"contactform\">\r\n");
      out.write("            \r\n");
      out.write("                <h2>Click Next</h2>\r\n");
      out.write("              <input type=\"submit\" value=\"Next\"/>\r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
 


//this was previously commented -----------------------------------------------------------------------------------
String songcont = null;
String sub=null;
//PrintWriter out = response.getWriter();
String str="Select * from song";
	int[] edit=new int[4000];
	int[] songid=new int[10];
	Statement stmt=null;
	String save=null;
	
			int e=0;
			  Database db=new Database();
                Connection con=db.dataConnection();
        		
        		String str1="select * from query";
        		try {
        			
        		stmt = con.createStatement();
        		ResultSet rs1=stmt.executeQuery(str1);
        		
        		while(rs1.next())
        		{
        			save=rs1.getString(1);
        		}
        	} catch (SQLException e1) {
        		// TODO Auto-generated catch block
        		e1.printStackTrace();
        	}
        	
			
try {
		
		stmt = con.createStatement();
	ResultSet rs=stmt.executeQuery(str);int l2=0;
	int f=0;
	 out.println("<form method='post' action='Save.jsp'><p>&nbsp;</p> ");
     out.println("<div class='background' height='332px' width='603'>");
     out.println("<font color='red' size='6px'>Search Results:</font>");
     out.println("<table  width='603' height='332' border='10' align='center' bordercolor='#FFFF00' >");
	while(rs.next())
	{
		songcont=rs.getString(7);
	//	matchingcode m=new matchingcode();
		
		if(save!=null){
	 l2=save.length();}
		if(l2!=0)
		{
		edit[e]=matchingcode.EditDistanceDP(songcont, save);
		songid[e]=rs.getInt(1);
		e++;
		
		}	

	}
		Statement stmt1=con.createStatement();
		for(f=0;f<e;f++)
		{String str4="Select * from song where songid="+songid[f]+"";
		
		String[] d= new String[10];
		int i=0;
		
		ResultSet rs1=stmt1.executeQuery(str4);
		 
       
	
		while(rs1.next())
		{
			System.out.println("servlet: "+songid[f]);
			out.println("<tr><td width='207' align='center' >"+rs1.getString(1)+"</td><td width='207'>"+rs1.getString(2)+"</td><td><input type='submit' name='download' class='submit'   value="+rs1.getString(2)+"></td><td><a href=select.jsp?song="+rs1.getString(2)+" '\'>Select</a></td></tr>");	
		  //rs.getString(2).toCharArray(); 
		 System.out.println("Serveltss: "+rs1.getString(2));
		 d[i]=rs1.getString(1);
		  
		}
		rs1.close();
		}
		
		
								
	out.println("</table>");
	out.println("</div>");
	out.println("<input type='button' name='Re-Rank' value='Re-Rank' >");
	out.println("</form>");out.println("</body>");
    out.println("</html>");
} catch (SQLException ex) {
	// TODO Auto-generated catch block
	ex.printStackTrace();
}


    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
